// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/WildEgor/g-cdn/internal/config"
	"github.com/WildEgor/g-cdn/internal/handlers"
	"github.com/WildEgor/g-cdn/internal/router"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*Server, error) {
	configurator := config.NewConfigurator()
	appConfig := config.NewAppConfig(configurator)
	healthCheckHandler := handlers.NewHealthCheckHandler(appConfig)
	routerRouter := router.NewRouter(healthCheckHandler)
	server := NewApp(appConfig, routerRouter)
	return server, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
